# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_18 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_18.setGeometry(QtCore.QRect(600, 330, 191, 141))
        self.groupBox_18.setStyleSheet("background-color: rgb(228, 255, 255)")
        self.groupBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_18.setObjectName("groupBox_18")
        self.widget = QtWidgets.QWidget(self.groupBox_18)
        self.widget.setGeometry(QtCore.QRect(10, 20, 172, 61))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Motor1ForwardOnOffButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.Motor1ForwardOnOffButton.setFont(font)
        self.Motor1ForwardOnOffButton.setStyleSheet("background-color: rgb(252, 238, 255);\n"
"color: black; \n"
"border-radius: 10px; border: 2px groove gray;\n"
"border-style: outset;")
        self.Motor1ForwardOnOffButton.setCheckable(True)
        self.Motor1ForwardOnOffButton.setObjectName("Motor1ForwardOnOffButton")
        self.horizontalLayout.addWidget(self.Motor1ForwardOnOffButton)
        self.Motor1BackwardOnOffButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.Motor1BackwardOnOffButton.setFont(font)
        self.Motor1BackwardOnOffButton.setStyleSheet("background-color: rgb(252, 238, 255);\n"
"color: black; \n"
"border-radius: 10px; border: 2px groove gray;\n"
"border-style: outset;")
        self.Motor1BackwardOnOffButton.setCheckable(True)
        self.Motor1BackwardOnOffButton.setObjectName("Motor1BackwardOnOffButton")
        self.horizontalLayout.addWidget(self.Motor1BackwardOnOffButton)
        self.widget1 = QtWidgets.QWidget(self.groupBox_18)
        self.widget1.setGeometry(QtCore.QRect(10, 80, 172, 61))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Motor2ForwardOnOffButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.Motor2ForwardOnOffButton.setFont(font)
        self.Motor2ForwardOnOffButton.setStyleSheet("background-color: rgb(252, 238, 255);\n"
"color: black; \n"
"border-radius: 10px; border: 2px groove gray;\n"
"border-style: outset;")
        self.Motor2ForwardOnOffButton.setCheckable(True)
        self.Motor2ForwardOnOffButton.setObjectName("Motor2ForwardOnOffButton")
        self.horizontalLayout_2.addWidget(self.Motor2ForwardOnOffButton)
        self.Motor2BackwardOnOffButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.Motor2BackwardOnOffButton.setFont(font)
        self.Motor2BackwardOnOffButton.setStyleSheet("background-color: rgb(252, 238, 255);\n"
"color: black; \n"
"border-radius: 10px; border: 2px groove gray;\n"
"border-style: outset;")
        self.Motor2BackwardOnOffButton.setCheckable(True)
        self.Motor2BackwardOnOffButton.setObjectName("Motor2BackwardOnOffButton")
        self.horizontalLayout_2.addWidget(self.Motor2BackwardOnOffButton)
        self.groupBox_22 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_22.setGeometry(QtCore.QRect(210, 350, 181, 121))
        self.groupBox_22.setStyleSheet("background-color: rgb(228, 255, 255);")
        self.groupBox_22.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_22.setObjectName("groupBox_22")
        self.widget2 = QtWidgets.QWidget(self.groupBox_22)
        self.widget2.setGeometry(QtCore.QRect(11, 24, 161, 61))
        self.widget2.setObjectName("widget2")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.ExitButton = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ExitButton.setFont(font)
        self.ExitButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: black; \n"
"border-radius: 10px; border: 2px groove gray;\n"
"border-style: outset;\n"
"\n"
"")
        self.ExitButton.setCheckable(True)
        self.ExitButton.setObjectName("ExitButton")
        self.gridLayout_22.addWidget(self.ExitButton, 2, 0, 1, 1)
        self.Button = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button.setFont(font)
        self.Button.setStyleSheet("background-color: rgb(0, 255, 100);\n"
"color: black; \n"
"border-radius: 10px; border: 2px groove gray;\n"
"border-style: outset;")
        self.Button.setCheckable(True)
        self.Button.setObjectName("Button")
        self.gridLayout_22.addWidget(self.Button, 1, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(400, 10, 191, 461))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet("background-color: rgb(228, 255, 255);")
        self.groupBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.UpdatePerfusionSettingButton = QtWidgets.QPushButton(self.groupBox_13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.UpdatePerfusionSettingButton.setFont(font)
        self.UpdatePerfusionSettingButton.setStyleSheet("background-color: rgb(255, 0, 100);\n"
"color: black; \n"
"border-radius: 5px; border: 2px groove gray;\n"
"border-style: outset;")
        self.UpdatePerfusionSettingButton.setObjectName("UpdatePerfusionSettingButton")
        self.gridLayout_11.addWidget(self.UpdatePerfusionSettingButton, 6, 0, 1, 1)
        self.StartStopPerfusionButton = QtWidgets.QPushButton(self.groupBox_13)
        self.StartStopPerfusionButton.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StartStopPerfusionButton.setFont(font)
        self.StartStopPerfusionButton.setStyleSheet("color: black; \n"
"border-radius: 5px; border: 2px groove gray;\n"
"border-style: outset;")
        self.StartStopPerfusionButton.setCheckable(True)
        self.StartStopPerfusionButton.setObjectName("StartStopPerfusionButton")
        self.gridLayout_11.addWidget(self.StartStopPerfusionButton, 7, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.FlowRateCB = QtWidgets.QComboBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FlowRateCB.setFont(font)
        self.FlowRateCB.setObjectName("FlowRateCB")
        self.FlowRateCB.addItem("")
        self.FlowRateCB.addItem("")
        self.FlowRateCB.addItem("")
        self.FlowRateCB.addItem("")
        self.FlowRateCB.addItem("")
        self.FlowRateCB.addItem("")
        self.FlowRateCB.addItem("")
        self.gridLayout_12.addWidget(self.FlowRateCB, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.PerfusionTimeCB = QtWidgets.QComboBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PerfusionTimeCB.setFont(font)
        self.PerfusionTimeCB.setObjectName("PerfusionTimeCB")
        self.PerfusionTimeCB.addItem("")
        self.PerfusionTimeCB.addItem("")
        self.PerfusionTimeCB.addItem("")
        self.PerfusionTimeCB.addItem("")
        self.PerfusionTimeCB.addItem("")
        self.PerfusionTimeCB.addItem("")
        self.PerfusionTimeCB.addItem("")
        self.PerfusionTimeCB.addItem("")
        self.PerfusionTimeCB.addItem("")
        self.gridLayout_14.addWidget(self.PerfusionTimeCB, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_16, 2, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.IntervalCB = QtWidgets.QComboBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IntervalCB.setFont(font)
        self.IntervalCB.setObjectName("IntervalCB")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.IntervalCB.addItem("")
        self.gridLayout_13.addWidget(self.IntervalCB, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_15, 3, 0, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.PressureLCD = QtWidgets.QLCDNumber(self.groupBox_20)
        self.PressureLCD.setDigitCount(4)
        self.PressureLCD.setObjectName("PressureLCD")
        self.gridLayout_19.addWidget(self.PressureLCD, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_20, 4, 0, 1, 1)
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_21.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.pHLCD = QtWidgets.QLCDNumber(self.groupBox_21)
        self.pHLCD.setDigitCount(4)
        self.pHLCD.setObjectName("pHLCD")
        self.gridLayout_20.addWidget(self.pHLCD, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_21, 5, 0, 1, 1)
        self.ResetPerusionButton = QtWidgets.QPushButton(self.groupBox_13)
        self.ResetPerusionButton.setStyleSheet("color: black; \n"
"border-radius: 5px; border: 2px groove gray;\n"
"border-style: outset;")
        self.ResetPerusionButton.setObjectName("ResetPerusionButton")
        self.gridLayout_11.addWidget(self.ResetPerusionButton, 8, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 10, 181, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background-color: rgb(228, 255, 255);")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Count5lcdNum = QtWidgets.QLCDNumber(self.groupBox_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Count5lcdNum.setFont(font)
        self.Count5lcdNum.setAutoFillBackground(False)
        self.Count5lcdNum.setDigitCount(4)
        self.Count5lcdNum.setProperty("value", 0.0)
        self.Count5lcdNum.setObjectName("Count5lcdNum")
        self.gridLayout_6.addWidget(self.Count5lcdNum, 1, 1, 1, 1)
        self.DryIceTareButton = QtWidgets.QPushButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.DryIceTareButton.setFont(font)
        self.DryIceTareButton.setCheckable(True)
        self.DryIceTareButton.setObjectName("DryIceTareButton")
        self.gridLayout_6.addWidget(self.DryIceTareButton, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Count5lcdNum_2 = QtWidgets.QLCDNumber(self.groupBox_11)
        self.Count5lcdNum_2.setAutoFillBackground(False)
        self.Count5lcdNum_2.setDigitCount(4)
        self.Count5lcdNum_2.setProperty("value", 0.0)
        self.Count5lcdNum_2.setObjectName("Count5lcdNum_2")
        self.gridLayout_8.addWidget(self.Count5lcdNum_2, 2, 0, 1, 1)
        self.PerfusionFluidTareButton = QtWidgets.QPushButton(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.PerfusionFluidTareButton.setFont(font)
        self.PerfusionFluidTareButton.setCheckable(True)
        self.PerfusionFluidTareButton.setObjectName("PerfusionFluidTareButton")
        self.gridLayout_8.addWidget(self.PerfusionFluidTareButton, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.WasteFluidTareButton = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.WasteFluidTareButton.setFont(font)
        self.WasteFluidTareButton.setCheckable(True)
        self.WasteFluidTareButton.setObjectName("WasteFluidTareButton")
        self.gridLayout_9.addWidget(self.WasteFluidTareButton, 1, 0, 1, 1)
        self.Count5lcdNum_3 = QtWidgets.QLCDNumber(self.groupBox_12)
        self.Count5lcdNum_3.setAutoFillBackground(False)
        self.Count5lcdNum_3.setDigitCount(4)
        self.Count5lcdNum_3.setProperty("value", 0.0)
        self.Count5lcdNum_3.setObjectName("Count5lcdNum_3")
        self.gridLayout_9.addWidget(self.Count5lcdNum_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_12, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(600, 10, 191, 311))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: rgb(228, 255, 255);")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Count5lcdNum_4 = QtWidgets.QLCDNumber(self.groupBox_9)
        self.Count5lcdNum_4.setAutoFillBackground(False)
        self.Count5lcdNum_4.setDigitCount(4)
        self.Count5lcdNum_4.setProperty("value", 0.0)
        self.Count5lcdNum_4.setObjectName("Count5lcdNum_4")
        self.gridLayout_5.addWidget(self.Count5lcdNum_4, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_19.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_19.setObjectName("groupBox_19")
        self.label_8 = QtWidgets.QLabel(self.groupBox_19)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 131, 20))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 200);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_19)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 131, 21))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 200);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_17.addWidget(self.groupBox_19, 3, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_17.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.Count5lcdNum_5 = QtWidgets.QLCDNumber(self.groupBox_17)
        self.Count5lcdNum_5.setAutoFillBackground(False)
        self.Count5lcdNum_5.setDigitCount(4)
        self.Count5lcdNum_5.setProperty("value", 0.0)
        self.Count5lcdNum_5.setObjectName("Count5lcdNum_5")
        self.gridLayout_15.addWidget(self.Count5lcdNum_5, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_17, 1, 0, 1, 1)
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_23.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.Count5lcdNum_6 = QtWidgets.QLCDNumber(self.groupBox_23)
        self.Count5lcdNum_6.setAutoFillBackground(False)
        self.Count5lcdNum_6.setDigitCount(4)
        self.Count5lcdNum_6.setProperty("value", 0.0)
        self.Count5lcdNum_6.setObjectName("Count5lcdNum_6")
        self.gridLayout_16.addWidget(self.Count5lcdNum_6, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_23, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(11, 11, 191, 461))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(228, 255, 255);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.CoolingOnOffButton = QtWidgets.QPushButton(self.groupBox_2)
        self.CoolingOnOffButton.setGeometry(QtCore.QRect(10, 350, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.CoolingOnOffButton.setFont(font)
        self.CoolingOnOffButton.setStyleSheet("background-color: rgb(255, 0, 100);\n"
"color: black; \n"
"border-radius: 10px; border: 2px groove gray;\n"
"border-style: outset;")
        self.CoolingOnOffButton.setCheckable(True)
        self.CoolingOnOffButton.setObjectName("CoolingOnOffButton")
        self.ExhaustOnOffButton = QtWidgets.QPushButton(self.groupBox_2)
        self.ExhaustOnOffButton.setGeometry(QtCore.QRect(10, 390, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.ExhaustOnOffButton.setFont(font)
        self.ExhaustOnOffButton.setStyleSheet("background-color: rgb(255, 0, 100);\n"
"color: black; \n"
"border-radius: 10px; border: 2px groove gray;\n"
"border-style: outset;")
        self.ExhaustOnOffButton.setCheckable(True)
        self.ExhaustOnOffButton.setObjectName("ExhaustOnOffButton")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 149, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.widget3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(10, 60, 167, 281))
        self.widget3.setObjectName("widget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget3)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.Count1lcdNum = QtWidgets.QLCDNumber(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Count1lcdNum.setFont(font)
        self.Count1lcdNum.setDigitCount(4)
        self.Count1lcdNum.setObjectName("Count1lcdNum")
        self.gridLayout.addWidget(self.Count1lcdNum, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget3)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Count2lcdNum = QtWidgets.QLCDNumber(self.groupBox_6)
        self.Count2lcdNum.setDigitCount(4)
        self.Count2lcdNum.setObjectName("Count2lcdNum")
        self.gridLayout_2.addWidget(self.Count2lcdNum, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget3)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Count3lcdNum = QtWidgets.QLCDNumber(self.groupBox_7)
        self.Count3lcdNum.setDigitCount(4)
        self.Count3lcdNum.setObjectName("Count3lcdNum")
        self.gridLayout_3.addWidget(self.Count3lcdNum, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget3)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Count4lcdNum = QtWidgets.QLCDNumber(self.groupBox_8)
        self.Count4lcdNum.setDigitCount(4)
        self.Count4lcdNum.setObjectName("Count4lcdNum")
        self.gridLayout_4.addWidget(self.Count4lcdNum, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.gridLayout_18.addWidget(self.groupBox_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_18.setTitle(_translate("MainWindow", "DEBUG Controls"))
        self.Motor1ForwardOnOffButton.setText(_translate("MainWindow", "Motor 1\n"
"Forward ON"))
        self.Motor1BackwardOnOffButton.setText(_translate("MainWindow", "Motor 1\n"
"Backward ON"))
        self.Motor2ForwardOnOffButton.setText(_translate("MainWindow", "Motor 2\n"
"Forward ON"))
        self.Motor2BackwardOnOffButton.setText(_translate("MainWindow", "Motor 2\n"
"Backward ON"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Connection"))
        self.ExitButton.setText(_translate("MainWindow", "EXIT"))
        self.Button.setText(_translate("MainWindow", "CONNECT"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Perfusion Control"))
        self.UpdatePerfusionSettingButton.setText(_translate("MainWindow", "Update Settings"))
        self.StartStopPerfusionButton.setText(_translate("MainWindow", "START Perfusion"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Perfusion flow rate (mL/min)"))
        self.FlowRateCB.setCurrentText(_translate("MainWindow", "Select Flow Rate"))
        self.FlowRateCB.setItemText(0, _translate("MainWindow", "Select Flow Rate"))
        self.FlowRateCB.setItemText(1, _translate("MainWindow", "100"))
        self.FlowRateCB.setItemText(2, _translate("MainWindow", "150"))
        self.FlowRateCB.setItemText(3, _translate("MainWindow", "200"))
        self.FlowRateCB.setItemText(4, _translate("MainWindow", "250"))
        self.FlowRateCB.setItemText(5, _translate("MainWindow", "300"))
        self.FlowRateCB.setItemText(6, _translate("MainWindow", "None"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Perfusion time (seconds)"))
        self.PerfusionTimeCB.setItemText(0, _translate("MainWindow", "Select Time     "))
        self.PerfusionTimeCB.setItemText(1, _translate("MainWindow", "30"))
        self.PerfusionTimeCB.setItemText(2, _translate("MainWindow", "45"))
        self.PerfusionTimeCB.setItemText(3, _translate("MainWindow", "60"))
        self.PerfusionTimeCB.setItemText(4, _translate("MainWindow", "75"))
        self.PerfusionTimeCB.setItemText(5, _translate("MainWindow", "90"))
        self.PerfusionTimeCB.setItemText(6, _translate("MainWindow", "105"))
        self.PerfusionTimeCB.setItemText(7, _translate("MainWindow", "120"))
        self.PerfusionTimeCB.setItemText(8, _translate("MainWindow", "None"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Perfusion Interval (minutes)"))
        self.IntervalCB.setItemText(0, _translate("MainWindow", "Select Time     "))
        self.IntervalCB.setItemText(1, _translate("MainWindow", "3"))
        self.IntervalCB.setItemText(2, _translate("MainWindow", "10"))
        self.IntervalCB.setItemText(3, _translate("MainWindow", "15"))
        self.IntervalCB.setItemText(4, _translate("MainWindow", "20"))
        self.IntervalCB.setItemText(5, _translate("MainWindow", "25"))
        self.IntervalCB.setItemText(6, _translate("MainWindow", "30"))
        self.IntervalCB.setItemText(7, _translate("MainWindow", "35"))
        self.IntervalCB.setItemText(8, _translate("MainWindow", "40"))
        self.IntervalCB.setItemText(9, _translate("MainWindow", "None"))
        self.groupBox_20.setTitle(_translate("MainWindow", "In-Line Pressure (mmHg)"))
        self.groupBox_21.setTitle(_translate("MainWindow", "pH (0-14)"))
        self.ResetPerusionButton.setText(_translate("MainWindow", "RESET"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Loadcell Feedbacks"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Dry ice (grams)"))
        self.DryIceTareButton.setText(_translate("MainWindow", "TARE"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Saline bag 1 (grams)"))
        self.PerfusionFluidTareButton.setText(_translate("MainWindow", "TARE"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Saline bag 2 (grams)"))
        self.WasteFluidTareButton.setText(_translate("MainWindow", "TARE"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Time"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Total time elapsed (Seconds)"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Motor Status"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Time until next perfusion(seconds)"))
        self.groupBox_23.setTitle(_translate("MainWindow", "No. of perfusion cycles completed"))
        self.groupBox.setTitle(_translate("MainWindow", "Cooling Control"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Temperature Feedbacks"))
        self.CoolingOnOffButton.setText(_translate("MainWindow", "COOLING ON"))
        self.ExhaustOnOffButton.setText(_translate("MainWindow", "OPEN EXHAUST"))
        self.label_3.setText(_translate("MainWindow", "Set Point = 6"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Top Temperature (°C)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Bottom Temperature (°C)"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Average Temperature (°C)"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Heart Temperature (°C)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

